{
 "title": "ansible-runner-service Metrics",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "ansible_hostname",
    "label": "Ansible Hostname",
    "query": "label_values(runner_service_duration_scrape_secs, hostname)"
   }
  ]
 },
 "panels": [
  {
   "title": "Managed Playbooks",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "runner_service_playbook_count{hostname=~\"($ansible_hostname)\"}"
    }
   ]
  },
  {
   "title": "Playbooks Running",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 4, "x": 4, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "runner_service_playbooks_active{hostname=~\"($ansible_hostname)\"}"
    }
   ]
  },
  {
   "title": "Playbook Activity for host '$ansible_hostname'",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 0 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "runner_service_playbooks_active{hostname=~\"($ansible_hostname)\"}",
     "legendFormat": "Playbooks Active"
    }
   ]
  },
  {
   "title": "Playbook Run Summary",
   "type": "table",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 0 },
   "targets": [
    {
     "expr": "runner_service_playbooks_status{hostname=~\"($ansible_hostname)\"}"
    }
   ]
  },
  {
   "title": "Task Status Over Time",
   "type": "graph",
   "gridPos": { "h": 9, "w": 13, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "none", "label": "# Tasks Run" }
   ],
   "targets": [
    {
     "expr": "runner_service_event_status{hostname=~\"($ansible_hostname)\"}",
     "legendFormat": "{{event_status}}"
    }
   ]
  },
  {
   "title": "$ansible_hostname CPU Busy %",
   "type": "graph",
   "gridPos": { "h": 9, "w": 11, "x": 13, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "100 - (avg by (instance) (irate(node_cpu_seconds_total{job=\"node\",mode=\"idle\",instance=~\"($ansible_hostname).*\"}[1m])) * 100)",
     "legendFormat": "{{Busy %}}"
    }
   ]
  }
 ]
}